name: Deploy Backend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        env:
          EC2_HOST: ${{ secrets.HOST_DNS }}
          EC2_USER: ${{ secrets.USERNAME }}
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          TARGET_DIR: ${{ secrets.TARGET_DIR }}
        run: |
          echo "$EC2_SSH_KEY" > private_key.pem
          chmod 600 private_key.pem

          ssh -vvv -o StrictHostKeyChecking=no -i private_key.pem $EC2_USER@$EC2_HOST << 'EOF'
            cd /home/ubuntu/backend

            pwd
            ls

            ssh-keyscan github.com >> ~/.ssh/known_hosts

            git pull origin main

            npm install

            pm2 restart backend || pm2 start app.js --name "backend"
          EOF